---
# Pylone pose in base_link frame.
# Default values match the simulation setup
# On the real robot, overwrite with scripts/localize_pylone.py output.

pylone_x: 0.7 # default 0.7
pylone_y: 0.0 # default 0.0
pylone_z: 0.8 # default 0.3 (to the ground)
pylone_quat: [0.0, 0.0, 0.0, 1.0] # default [0.0, 0.0, 0.0, 1.0]
