arm_left_1_joint_inertia_shaping_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    reference_interfaces: [arm_left_1_joint/effort]
    command_interfaces: [arm_left_1_joint/effort]

arm_left_2_joint_inertia_shaping_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    reference_interfaces: [arm_left_2_joint/effort]
    command_interfaces: [arm_left_2_joint/effort]

arm_left_3_joint_inertia_shaping_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    reference_interfaces: [arm_left_3_joint/effort]
    command_interfaces: [arm_left_3_joint/effort]

arm_left_4_joint_inertia_shaping_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    reference_interfaces: [arm_left_4_joint/effort]
    command_interfaces: [arm_left_4_joint/effort]

arm_left_5_joint_inertia_shaping_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    reference_interfaces: [arm_left_5_joint/effort]
    command_interfaces: [arm_left_5_joint/effort]

arm_left_6_joint_inertia_shaping_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    reference_interfaces: [arm_left_6_joint/effort]
    command_interfaces: [arm_left_6_joint/effort]

arm_left_7_joint_inertia_shaping_controller:
  ros__parameters:
    type: linear_feedback_controller/PassthroughController
    reference_interfaces: [arm_left_7_joint/effort]
    command_interfaces: [arm_left_7_joint/effort]