joint_state_estimator:
  ros__parameters:
    type: linear_feedback_controller/JointStateEstimator
    state_interfaces: [arm_left_1_joint/position, arm_left_2_joint/position, arm_left_3_joint/position,
      arm_left_4_joint/position, arm_left_5_joint/position, arm_left_6_joint/position,
      arm_left_7_joint/position, arm_left_1_joint/velocity, arm_left_2_joint/velocity,
      arm_left_3_joint/velocity, arm_left_4_joint/velocity, arm_left_5_joint/velocity,
      arm_left_6_joint/velocity, arm_left_7_joint/velocity, arm_left_1_joint/effort, arm_left_2_joint/effort,
      arm_left_3_joint/effort, arm_left_4_joint/effort, arm_left_5_joint/effort, arm_left_6_joint/effort,
      arm_left_7_joint/effort]
    command_interfaces: [linear_feedback_controller/arm_left_1_joint/position, linear_feedback_controller/arm_left_2_joint/position,
      linear_feedback_controller/arm_left_3_joint/position, linear_feedback_controller/arm_left_4_joint/position,
      linear_feedback_controller/arm_left_5_joint/position, linear_feedback_controller/arm_left_6_joint/position,
      linear_feedback_controller/arm_left_7_joint/position, linear_feedback_controller/arm_left_1_joint/velocity,
      linear_feedback_controller/arm_left_2_joint/velocity, linear_feedback_controller/arm_left_3_joint/velocity,
      linear_feedback_controller/arm_left_4_joint/velocity, linear_feedback_controller/arm_left_5_joint/velocity,
      linear_feedback_controller/arm_left_6_joint/velocity, linear_feedback_controller/arm_left_7_joint/velocity,
      linear_feedback_controller/arm_left_1_joint/effort, linear_feedback_controller/arm_left_2_joint/effort,
      linear_feedback_controller/arm_left_3_joint/effort, linear_feedback_controller/arm_left_4_joint/effort,
      linear_feedback_controller/arm_left_5_joint/effort, linear_feedback_controller/arm_left_6_joint/effort,
      linear_feedback_controller/arm_left_7_joint/effort]